apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    app: webhook

